### ISSUE TITLE
Understanding the program

### ISSUE THREAD

**Issue by armandeeps** [radiantly/Invisiwind#1]
I am unable to get the program to work when launching from the project, only the installed version.  What is the difference?  

Additionally, I wanted to get a better understanding of the software if you have the time to chat.

**Comment by radiantly** [comment]
Not sure why you're unable to get it to work when launching the project - If you take a look at the [workflow file](https://github.com/radiantly/Invisiwind/blob/main/.github/workflows/build.yml), you'll notice that both the installer and the portable version are built from the project using `msbuild`. Maybe you could try replicating that?

**Comment by armandeeps** [comment]
I am working on a similar injection program and am unable to get it working - are you able to help debug?  Thanks.

**Comment by armandeeps** [comment]
When I run it from the visual studio debugger, there is no output when I enter `hide spotify.exe` and it is not hidden from screen captures.
