### ISSUE TITLE
Running from VS does not work, but works fine from portable

### ISSUE THREAD

**Issue by armandeeps** [radiantly/Invisiwind#2]
The reason I bring this up is because I am working on a similar injection tool and am having an issue where the dll does not run after `CreateRemoteThreadEx()` call.
![Demonstration](https://user-images.githubusercontent.com/68488740/124818054-6831b380-df1f-11eb-9a8d-5121bdef24d4.gif)

**Comment by radiantly** [comment]
Using the visual studio debugger does not work. I didn't look into the issue into much detail, but I'd assume that it's because of the fact the debugger itself is doing some hooking on the running program. Instead, I'd suggest building and running it directly.

**Comment by armandeeps** [comment]
Running from `\Build\bin\debug\Invisiwind.exe\` does not work

**Comment by radiantly** [comment]
I trust you can troubleshoot the problem? Start adding debugging statements to check what's executing and what's not. Currently, I cannot think of any specific reason for why your build fails, but I am of the opinion that the project itself is not at fault as GitHub Actions/msbuild manages to build the project without issues. Do let me know if you do find something.

**Comment by radiantly** [comment]
Looking at the gif you posted again - are you building the dll project too? It looks like you are only building the main project.

**Comment by armandeeps** [comment]
Yeah I forgot to build the .dlls, whoops.  It works now from the exe, but not the debugger, which makes sense, I would assume VS is running the application in some sort of sandbox.

Thanks a bunch!

If you get the chance to take a look, do you have any idea why something like this wouldn't work.  When called on chrome it fails on `CreateRemoteThreadEx`.

```
main()
{
    HANLDE currHandle = getHandle();
    CHAR pathName[256] = getPathName();
    HMODULE k32Handle;
    GetModuleHandleEx(0, L"kernel32.dll", &k32Handle);
    LPVOID k32Addr = GetProcAddress(k32Handle, "LoadLibraryW");
    inject(currHandle, pathName, k32Addr);
}

getHandle()
{
    //...
    return handle;
}

getPathName()
{
    //...
    return pathName;
}

BOOL inject(HANDLE procHandle, CHAR* dllPath, LPVOID k32Addr)
{
    int code = 4;
    size_t dllPathLen = (strlen(dllPath) + 1) * sizeof(wchar_t);

    std::cout << "Injecting\nAllocating virtual memory\n";
    LPVOID vAddr = VirtualAllocEx(procHandle, NULL, dllPathLen, MEM_COMMIT, PAGE_READWRITE);
    if (vAddr)
    {
        code = 5;
        std::cout << "Writing\n";

        if (WriteProcessMemory(procHandle, vAddr, dllPath, dllPathLen, NULL))
        {
            code = 6;
            std::cout << "Creating remote thread\n";

            HANDLE rThread = CreateRemoteThreadEx(procHandle, NULL, 0, static_cast<LPTHREAD_START_ROUTINE>(k32Addr), vAddr, 0, NULL, NULL);
            if (rThread)
            {
                std::cout << "SUCCESSFUL INJECTION\n\n";
                WaitForSingleObject(rThread, INFINITE);
                CloseHandle(rThread); 
                CloseHandle(procHandle);
            }
            else
            {
                std::cout << "Error [" << code << "] : Failed to create remote thread\n\n";
            }
        }
        else
        {
            std::cout << "Error [" << code << "] : Failed to write to process\n\n";
        }
    }
    else
    {
        std::cout << "Error [" << code << "] : Failed to allocate memory for process\n\n";
    }
    //printErr(code);
    return FALSE;
}
```
