### ISSUE TITLE
No Issue. I created a project inspred by yours.

### ISSUE THREAD

**Issue by AbortLarboard** [radiantly/Invisiwind#5]
Thanks a lot Joshua for Invisiwind and the dll source!

I kinda tried to do the same but with a GUI and some more features. Beware this is my first project and it is still in early development stage. I hope that you are okay with copying some of yours. 

here is the [link to my tool called Curtains](https://github.com/AbortLarboard/curtains_dev)

Regards,
Julian

**Comment by radiantly** [comment]
Looks great!
